version: "3.8"
services:
  inbank-api:
    image: inbank-api:latest
    container_name: inbank-api
    hostname: inbank-api
    ports:
      - '8080:8080'
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dspring.profiles.active=dev
  inbank-frontend:
    image: inbank-frontend:latest
    container_name: inbank-frontend
    hostname: inbank-frontend
    depends_on:
      - inbank-api
    ports:
      - '8081:80'